https://www.wunderground.com/weather/api/d/docs API key: 2bd9def127e30dea

In [9]:
import requests
import json
f = requests.get('http://api.wunderground.com/api/2bd9def127e30dea/geolookup/conditions/q/IA/Cedar_Rapids.json')
json_string = f.json()
parsed_json = json_string
# parsed_json = json.loads(json_string)
location = parsed_json['location']['city']
temp_f = parsed_json['current_observation']['temp_f']
print("Current temperature in %s is: %s" % (location, temp_f))
f.close()

Current temperature in Cedar Rapids is: 57.9

In [11]:
# json_string

In [ ]:
http://api.wunderground.com/api/2bd9def127e30dea/history_YYYYMMDD/q/CA/San_Francisco.json

In [14]:
f = requests.get('http://api.wunderground.com/api/2bd9def127e30dea/history_20170105/q/TX/Austin.json')
json_string = f.json()
f.close()

In [38]:
json.dumps(json_string['history']['dailysummary'])

'[{"date": {"pretty": "12:00 PM CST on January 05, 2017", "year": "2017", "mon": "01", "mday": "05", "hour": "12", "min": "00", "tzname": "America/Chicago"}, "fog": "0", "rain": "0", "snow": "0", "snowfallm": "0.00", "snowfalli": "0.00", "monthtodatesnowfallm": "", "monthtodatesnowfalli": "", "since1julsnowfallm": "", "since1julsnowfalli": "", "snowdepthm": "", "snowdepthi": "", "hail": "0", "thunder": "0", "tornado": "0", "meantempm": "9", "meantempi": "49", "meandewptm": "2", "meandewpti": "35", "meanpressurem": "1014", "meanpressurei": "29.96", "meanwindspdm": "6", "meanwindspdi": "4", "meanwdire": "", "meanwdird": "12", "meanvism": "16", "meanvisi": "10", "humidity": "", "maxtempm": "17", "maxtempi": "62", "mintempm": "1", "mintempi": "34", "maxhumidity": "79", "minhumidity": "50", "maxdewptm": "8", "maxdewpti": "47", "mindewptm": "-8", "mindewpti": "18", "maxpressurem": "1020", "maxpressurei": "30.12", "minpressurem": "1011", "minpressurei": "29.87", "maxwspdm": "24", "maxwspdi": "15", "minwspdm": "0", "minwspdi": "0", "maxvism": "16", "maxvisi": "10", "minvism": "11", "minvisi": "7", "gdegreedays": "0", "heatingdegreedays": "16", "coolingdegreedays": "0", "precipm": "0.00", "precipi": "0.00", "precipsource": "", "heatingdegreedaysnormal": "", "monthtodateheatingdegreedays": "", "monthtodateheatingdegreedaysnormal": "", "since1sepheatingdegreedays": "", "since1sepheatingdegreedaysnormal": "", "since1julheatingdegreedays": "", "since1julheatingdegreedaysnormal": "", "coolingdegreedaysnormal": "", "monthtodatecoolingdegreedays": "", "monthtodatecoolingdegreedaysnormal": "", "since1sepcoolingdegreedays": "", "since1sepcoolingdegreedaysnormal": "", "since1jancoolingdegreedays": "", "since1jancoolingdegreedaysnormal": ""}]'

In [44]:
import pandas as pd
test = pd.DataFrame(json_string['history']['dailysummary'])#, orient='records')

In [45]:
test

,coolingdegreedays,coolingdegreedaysnormal,date,fog,gdegreedays,hail,heatingdegreedays,heatingdegreedaysnormal,humidity,maxdewpti,...,since1sepcoolingdegreedaysnormal,since1sepheatingdegreedays,since1sepheatingdegreedaysnormal,snow,snowdepthi,snowdepthm,snowfalli,snowfallm,thunder,tornado
0,0,,"{'pretty': '12:00 PM CST on January 05, 2017',...",0,0,0,16,,,47,...,,,,0,,,0.00,0.00,0,0

In [94]:
a = test['date'].values.tolist()

In [109]:
a = str(a)[1:len(str(a))-1]

In [113]:
a = a.replace("'",'"')

In [114]:
b = json.loads(a)
b

{'hour': '12',
 'mday': '05',
 'min': '00',
 'mon': '01',
 'pretty': '12:00 PM CST on January 05, 2017',
 'tzname': 'America/Chicago',
 'year': '2017'}

In [120]:
type(b)

dict

In [126]:
c = pd.DataFrame.from_dict(b, orient='index')
c

                                       0
pretty  12:00 PM CST on January 05, 2017
year                                2017
mon                                   01
mday                                  05
hour                                  12
min                                   00
tzname                   America/Chicago

In [127]:
c.T

                             pretty  year mon mday hour min           tzname
0  12:00 PM CST on January 05, 2017  2017  01   05   12  00  America/Chicago

In [132]:
test = pd.concat([test, c.T], axis=1)

In [133]:
test

,coolingdegreedays,coolingdegreedaysnormal,date,fog,gdegreedays,hail,heatingdegreedays,heatingdegreedaysnormal,humidity,maxdewpti,...,snowfallm,thunder,tornado,pretty,year,mon,mday,hour,min,tzname
0,0,,"{'pretty': '12:00 PM CST on January 05, 2017',...",0,0,0,16,,,47,...,0.00,0,0,"12:00 PM CST on January 05, 2017",2017,01,05,12,00,America/Chicago

# Now define functions to do this for us

In [144]:
def pull_data(date):
    f = requests.get('http://api.wunderground.com/api/2bd9def127e30dea/history_'+date+'/q/TX/Austin.json')
    json_string = f.json()
    f.close()
    
    current_df = pd.DataFrame(json_string['history']['dailysummary'])
    a = current_df['date'].values.tolist()
    a = str(a)[1:len(str(a))-1]
    a = a.replace("'",'"')
    b = json.loads(a)
    c = pd.DataFrame.from_dict(b, orient='index')
    current_df = pd.concat([current_df, c.T], axis=1)
    
    return current_df

In [145]:
def stack_df(old_df, new_df):
    stacked_df = pd.concat([old_df,new_df], axis=0)
    return stacked_df

In [146]:
# Test it out
dates = ['20170101', '20170102']

# Intialize our dataframe 
Only getting 2016 data, as we have a full dataset for that

In [155]:
df = pull_data('20160101')

In [156]:
df

,coolingdegreedays,coolingdegreedaysnormal,date,fog,gdegreedays,hail,heatingdegreedays,heatingdegreedaysnormal,humidity,maxdewpti,...,snowfallm,thunder,tornado,pretty,year,mon,mday,hour,min,tzname
0,0,0,"{'pretty': '12:00 PM CST on January 01, 2016',...",0,0,0,19,14,,36,...,0.00,0,0,"12:00 PM CST on January 01, 2016",2016,01,01,12,00,America/Chicago

In [158]:
path = 'D:/Users/Bryan Lanier/Data/Traffic_Weather/'

In [179]:
# Load dataframe with the dates 
dates_df = pd.read_csv(path+'Bluetooth_Travel_Sensors_-Traffic_Match_Summary_Records__TMSR_.csv', usecols=['timestamp'])
print(dates_df.shape[0])
dates_df.head()

12006783

                timestamp
0  01/10/2016 03:30:00 AM
1  01/10/2016 03:30:00 AM
2  01/10/2016 03:30:00 AM
3  01/10/2016 03:30:00 AM
4  01/10/2016 03:30:00 AM

In [180]:
dates_df['timestamp'][0][:10]

'01/10/2016'

In [181]:
def get_day(x):
    return int(x[3:5])

def get_month(x):
    return int(x[0:2])

def get_year(x):
    return int(x[6:10])

def kill_time(x):
    return x[:10]

In [182]:
dates_df['timestamp'] = dates_df['timestamp'].apply(lambda x: kill_time(x))
dates_df['Day'] = dates_df['timestamp'].apply(lambda x: get_day(x))
dates_df['Month'] = dates_df['timestamp'].apply(lambda x: get_month(x))
dates_df['Year'] = dates_df['timestamp'].apply(lambda x: get_year(x))

In [183]:
dates_df = dates_df.loc[dates_df['Year']==2016]
dates_df = dates_df.drop_duplicates()
print(dates_df.shape[0])
dates_df.head()

366

        timestamp  Day  Month  Year
0      01/10/2016   10      1  2016
53     01/01/2016    1      1  2016
13006  01/02/2016    2      1  2016
13223  01/23/2016   23      1  2016
13440  01/27/2016   27      1  2016

In [184]:
# Sort so dates are in order 
dates_df = dates_df.sort_values(by=['Month', 'Day'])
dates_df.head()

         timestamp  Day  Month  Year
53      01/01/2016    1      1  2016
13006   01/02/2016    2      1  2016
30483   01/03/2016    3      1  2016
121254  01/04/2016    4      1  2016
124992  01/05/2016    5      1  2016

In [167]:
def make_dates(x):
    date = x[6:10] + x[0:2] + x[3:5]
    return date

In [186]:
dates_list = dates_df['timestamp'].apply(lambda x: make_dates(x))
len(dates_list)

366

In [190]:
dates_list = dates_list.values.tolist()

In [195]:
dlist = dates_list[1:] #already have 01/01/2016

# Run the loop

In [199]:
df = pull_data('20160101')
df

,coolingdegreedays,coolingdegreedaysnormal,date,fog,gdegreedays,hail,heatingdegreedays,heatingdegreedaysnormal,humidity,maxdewpti,...,snowfallm,thunder,tornado,pretty,year,mon,mday,hour,min,tzname
0,0,0,"{'pretty': '12:00 PM CST on January 01, 2016',...",0,0,0,19,14,,36,...,0.00,0,0,"12:00 PM CST on January 01, 2016",2016,01,01,12,00,America/Chicago

In [201]:
import time

i = 0
for d in dlist:
    temp_df = pull_data(d)
    df = stack_df(df, temp_df)
    i += 1
    if i == 10:
        i = 0
        print('Sleeping, last date pulled was', d)
        time.sleep(60) #API limit is 10 per min 

df

Sleeping, last date pulled was 20160111
Sleeping, last date pulled was 20160121
Sleeping, last date pulled was 20160131
Sleeping, last date pulled was 20160210
Sleeping, last date pulled was 20160220
Sleeping, last date pulled was 20160301
Sleeping, last date pulled was 20160311
Sleeping, last date pulled was 20160321
Sleeping, last date pulled was 20160331
Sleeping, last date pulled was 20160410
Sleeping, last date pulled was 20160420
Sleeping, last date pulled was 20160430
Sleeping, last date pulled was 20160510
Sleeping, last date pulled was 20160520
Sleeping, last date pulled was 20160530
Sleeping, last date pulled was 20160609
Sleeping, last date pulled was 20160619
Sleeping, last date pulled was 20160629
Sleeping, last date pulled was 20160709
Sleeping, last date pulled was 20160719
Sleeping, last date pulled was 20160729
Sleeping, last date pulled was 20160808
Sleeping, last date pulled was 20160818
Sleeping, last date pulled was 20160828
Sleeping, last date pulled was 20160907
Sleeping, last date pulled was 20160917
Sleeping, last date pulled was 20160927
Sleeping, last date pulled was 20161007
Sleeping, last date pulled was 20161017
Sleeping, last date pulled was 20161027
Sleeping, last date pulled was 20161106
Sleeping, last date pulled was 20161116
Sleeping, last date pulled was 20161126
Sleeping, last date pulled was 20161206
Sleeping, last date pulled was 20161216
Sleeping, last date pulled was 20161226

,coolingdegreedays,coolingdegreedaysnormal,date,fog,gdegreedays,hail,heatingdegreedays,heatingdegreedaysnormal,humidity,maxdewpti,...,snowfallm,thunder,tornado,pretty,year,mon,mday,hour,min,tzname
0,0,0,"{'pretty': '12:00 PM CST on January 01, 2016',...",0,0,0,19,14,,36,...,0.00,0,0,"12:00 PM CST on January 01, 2016",2016,01,01,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 02, 2016',...",0,0,0,20,14,,42,...,0.00,0,0,"12:00 PM CST on January 02, 2016",2016,01,02,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 03, 2016',...",0,2,0,13,14,,43,...,0.00,0,0,"12:00 PM CST on January 03, 2016",2016,01,03,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 04, 2016',...",0,0,0,17,14,,33,...,0.00,0,0,"12:00 PM CST on January 04, 2016",2016,01,04,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 05, 2016',...",0,0,0,19,14,,40,...,0.00,0,0,"12:00 PM CST on January 05, 2016",2016,01,05,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 06, 2016',...",0,0,0,15,14,,52,...,0.00,1,0,"12:00 PM CST on January 06, 2016",2016,01,06,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 07, 2016',...",1,10,0,4,14,,53,...,0.00,0,0,"12:00 PM CST on January 07, 2016",2016,01,07,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 08, 2016',...",0,4,0,10,14,,57,...,0.00,1,0,"12:00 PM CST on January 08, 2016",2016,01,08,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 09, 2016',...",0,0,0,17,14,,44,...,0.00,0,0,"12:00 PM CST on January 09, 2016",2016,01,09,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 10, 2016',...",0,0,0,23,14,,28,...,0.00,0,0,"12:00 PM CST on January 10, 2016",2016,01,10,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 11, 2016',...",0,0,0,20,14,,32,...,0.00,0,0,"12:00 PM CST on January 11, 2016",2016,01,11,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 12, 2016',...",0,0,0,15,14,,39,...,0.00,0,0,"12:00 PM CST on January 12, 2016",2016,01,12,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 13, 2016',...",0,2,0,13,14,,42,...,0.00,0,0,"12:00 PM CST on January 13, 2016",2016,01,13,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 14, 2016',...",0,8,0,6,14,,55,...,0.00,0,0,"12:00 PM CST on January 14, 2016",2016,01,14,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 15, 2016',...",0,10,0,6,14,,53,...,0.00,0,0,"12:00 PM CST on January 15, 2016",2016,01,15,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 16, 2016',...",0,3,0,11,14,,43,...,0.00,0,0,"12:00 PM CST on January 16, 2016",2016,01,16,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 17, 2016',...",0,0,0,20,14,,35,...,0.00,0,0,"12:00 PM CST on January 17, 2016",2016,01,17,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 18, 2016',...",0,0,0,17,14,,38,...,0.00,0,0,"12:00 PM CST on January 18, 2016",2016,01,18,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 19, 2016',...",0,6,0,9,14,,51,...,0.00,0,0,"12:00 PM CST on January 19, 2016",2016,01,19,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 20, 2016',...",0,1,0,14,14,,51,...,0.00,0,0,"12:00 PM CST on January 20, 2016",2016,01,20,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 21, 2016',...",0,4,0,11,14,,56,...,0.00,0,0,"12:00 PM CST on January 21, 2016",2016,01,21,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 22, 2016',...",0,0,0,19,14,,30,...,0.00,0,0,"12:00 PM CST on January 22, 2016",2016,01,22,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 23, 2016',...",0,0,0,21,13,,32,...,0.00,0,0,"12:00 PM CST on January 23, 2016",2016,01,23,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 24, 2016',...",0,2,0,12,13,,52,...,0.00,0,0,"12:00 PM CST on January 24, 2016",2016,01,24,12,00,America/Chicago
0,1,0,"{'pretty': '12:00 PM CST on January 25, 2016',...",0,14,0,0,13,,57,...,0.00,0,0,"12:00 PM CST on January 25, 2016",2016,01,25,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 26, 2016',...",0,1,0,14,13,,36,...,0.00,0,0,"12:00 PM CST on January 26, 2016",2016,01,26,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 27, 2016',...",0,0,0,17,13,,30,...,0.00,0,0,"12:00 PM CST on January 27, 2016",2016,01,27,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 28, 2016',...",0,2,0,13,13,,36,...,0.00,0,0,"12:00 PM CST on January 28, 2016",2016,01,28,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 29, 2016',...",0,7,0,8,13,,39,...,0.00,0,0,"12:00 PM CST on January 29, 2016",2016,01,29,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on January 30, 2016',...",0,10,0,3,13,,56,...,0.00,0,0,"12:00 PM CST on January 30, 2016",2016,01,30,12,00,America/Chicago
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0,1,"{'pretty': '12:00 PM CST on December 02, 2016'...",0,8,0,7,11,,57,...,0.00,0,0,"12:00 PM CST on December 02, 2016",2016,12,02,12,00,America/Chicago
0,0,1,"{'pretty': '12:00 PM CST on December 03, 2016'...",0,0,0,14,11,,50,...,0.00,0,0,"12:00 PM CST on December 03, 2016",2016,12,03,12,00,America/Chicago
0,0,1,"{'pretty': '12:00 PM CST on December 04, 2016'...",0,0,0,14,11,,49,...,0.00,0,0,"12:00 PM CST on December 04, 2016",2016,12,04,12,00,America/Chicago
0,0,1,"{'pretty': '12:00 PM CST on December 05, 2016'...",0,0,0,15,11,,50,...,0.00,0,0,"12:00 PM CST on December 05, 2016",2016,12,05,12,00,America/Chicago
0,0,1,"{'pretty': '12:00 PM CST on December 06, 2016'...",1,0,0,14,11,,48,...,0.00,0,0,"12:00 PM CST on December 06, 2016",2016,12,06,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 07, 2016'...",0,0,0,17,12,,48,...,0.00,0,0,"12:00 PM CST on December 07, 2016",2016,12,07,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 08, 2016'...",0,0,0,21,12,,44,...,0.00,0,0,"12:00 PM CST on December 08, 2016",2016,12,08,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 09, 2016'...",0,0,0,25,12,,26,...,0.00,0,0,"12:00 PM CST on December 09, 2016",2016,12,09,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 10, 2016'...",0,0,0,21,12,,50,...,0.00,0,0,"12:00 PM CST on December 10, 2016",2016,12,10,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 11, 2016'...",1,8,0,6,12,,61,...,0.00,0,0,"12:00 PM CST on December 11, 2016",2016,12,11,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 12, 2016'...",0,6,0,8,13,,52,...,0.00,0,0,"12:00 PM CST on December 12, 2016",2016,12,12,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 13, 2016'...",0,14,0,1,13,,60,...,0.00,0,0,"12:00 PM CST on December 13, 2016",2016,12,13,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 14, 2016'...",0,0,0,15,13,,48,...,0.00,0,0,"12:00 PM CST on December 14, 2016",2016,12,14,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 15, 2016'...",0,0,0,15,13,,43,...,0.00,0,0,"12:00 PM CST on December 15, 2016",2016,12,15,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 16, 2016'...",0,8,0,6,13,,61,...,0.00,0,0,"12:00 PM CST on December 16, 2016",2016,12,16,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 17, 2016'...",0,6,0,10,13,,67,...,0.00,0,0,"12:00 PM CST on December 17, 2016",2016,12,17,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 18, 2016'...",0,0,0,33,13,,18,...,0.00,0,0,"12:00 PM CST on December 18, 2016",2016,12,18,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 19, 2016'...",0,0,0,31,14,,17,...,0.00,0,0,"12:00 PM CST on December 19, 2016",2016,12,19,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 20, 2016'...",0,0,0,18,14,,25,...,0.00,0,0,"12:00 PM CST on December 20, 2016",2016,12,20,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 21, 2016'...",0,6,0,8,14,,40,...,0.00,0,0,"12:00 PM CST on December 21, 2016",2016,12,21,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 22, 2016'...",0,8,0,6,14,,40,...,0.00,0,0,"12:00 PM CST on December 22, 2016",2016,12,22,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 23, 2016'...",1,10,0,5,14,,64,...,0.00,0,0,"12:00 PM CST on December 23, 2016",2016,12,23,12,00,America/Chicago
0,7,0,"{'pretty': '12:00 PM CST on December 24, 2016'...",0,20,0,0,14,,68,...,0.00,0,0,"12:00 PM CST on December 24, 2016",2016,12,24,12,00,America/Chicago
0,9,0,"{'pretty': '12:00 PM CST on December 25, 2016'...",0,24,0,0,14,,67,...,0.00,0,0,"12:00 PM CST on December 25, 2016",2016,12,25,12,00,America/Chicago
0,12,0,"{'pretty': '12:00 PM CST on December 26, 2016'...",0,28,0,0,14,,70,...,0.00,0,0,"12:00 PM CST on December 26, 2016",2016,12,26,12,00,America/Chicago
0,4,0,"{'pretty': '12:00 PM CST on December 27, 2016'...",0,19,0,0,14,,68,...,0.00,0,0,"12:00 PM CST on December 27, 2016",2016,12,27,12,00,America/Chicago
0,8,0,"{'pretty': '12:00 PM CST on December 28, 2016'...",0,22,0,0,14,,67,...,0.00,0,0,"12:00 PM CST on December 28, 2016",2016,12,28,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 29, 2016'...",0,9,0,5,14,,65,...,0.00,0,0,"12:00 PM CST on December 29, 2016",2016,12,29,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 30, 2016'...",0,1,0,13,14,,34,...,0.00,0,0,"12:00 PM CST on December 30, 2016",2016,12,30,12,00,America/Chicago
0,0,0,"{'pretty': '12:00 PM CST on December 31, 2016'...",0,14,0,1,14,,61,...,0.00,0,0,"12:00 PM CST on December 31, 2016",2016,12,31,12,00,America/Chicago

In [202]:
df.to_csv(path+'pulled_weather_data_2016.csv')