In [1]:
import numpy as np
import pandas as pd

In [170]:
# Create a list of champions - to be used for subreddits URLs
# There are some special cases, which will be explained next cell...

mains = ["Aatrox","Ahri","Akali","Amumu","Anivia","Annie","Ashe","Aurelion_Sol_",
         "Azir","Bard",

"Blitzcrank",

"Brand",

"Braum",

"Caitlyn",

"Camille",

"Cassiopeia",

"ChoGath",

"Corki",

"Darius",

"Diana",

"DrMundo",

"Ekko",

"Elise",

"Evelynn",

"Ezreal",

"Fiddlesticks",

"Fiora",

"Fizz",

"Galio",

"Gangplank",

"Garen",

"Gnar",

"Gragas",

"Graves",

"Hecarim",

"Heimerdinger",

"Irelia",

"Ivern",

"JarvanIV",

"Jax",

"Jayce",

"Jhin",

"Kalista",

"Karma",

"Karthus",

"Kassadin",

"Katarina",

"Kayle",

"Kayn",

"Kennen",

"KhaZix",


"Kled",

"KogMaw",

"LeBlanc",

"LeeSin",

"Leona",

"Lissandra",

"Lucian",

"Lulu",

"Malphite",

"Malzahar",

"Maokai",

"MasterYi",

"MissFortune",

"Mordekaiser",

"Morgana",

"Nami",

"Nasus",

"Nautilus",

"Nidalee",

"Nocturne",

"Nunu",

"Olaf",

"Orianna",

"Ornn",

"Pantheon",

"Poppy",

"Quinn",

"Rakan",

"Rammus",

"RekSai",

"Renekton",

"Rengar",

"Riven",

"Rumble",

"Ryze",

"Sejuani",

"Shaco",

"Shyvana",

"Singed",

"Skarner",

"Sona",

"Soraka",

"Swain",

"Syndra",

"TahmKench",

"Taliyah",

"Talon",

"Taric",

"Thresh",

"Tristana",

"Trundle",

"Tryndamere",

"TwistedFate",

"Twitch",

"Udyr",

"Urgot",

"Varus",

"Vayne",

"Veigar",

"Vi",

"Viktor",

"Vladimir",

"Volibear",

"Warwick",

"Wukong",

"Xayah",

"Xerath",

"XinZhao",

"Yasuo",

"Yorick",

"Zed",

"Ziggs",

"Zilean",

"Zoe",

"Zyra"]

In [171]:
mains_with_reddit = []
for i in range(len(mains)):
    mains_with_reddit.append(str(mains[i])+'mains')

In [172]:
main_sub_names = mains_with_reddit

main_sub_names.append('thesecretweapon')
main_sub_names.append('velkoz')
main_sub_names.append('TeemoTalk')
main_sub_names.append('Sivir')
main_sub_names.append('DirtySionMains')
main_sub_names.append('Shen')
main_sub_names.append('Lux')
main_sub_names.append('Kindred')
main_sub_names.append('leagueofjinx')
main_sub_names.append('Janna')
main_sub_names.append('Illaoi')
main_sub_names.append('Draven')
main_sub_names.append('Alistar')

In [173]:
# Get the names just right...
read_name = []

for i in range(len(main_sub_names)):
    read_name.append(str(main_sub_names[i]) + '_df.csv')

# read_name

In [174]:
clean_champ_names = mains

clean_champ_names.append('Zac')
clean_champ_names.append('Velkoz')
clean_champ_names.append('Teemo')
clean_champ_names.append('Sivir')
clean_champ_names.append('Sion')
clean_champ_names.append('Shen')
clean_champ_names.append('Lux')
clean_champ_names.append('Kindred')
clean_champ_names.append('Jinx')
clean_champ_names.append('Janna')
clean_champ_names.append('Illaoi')
clean_champ_names.append('Draven')
clean_champ_names.append('Alistar')

In [177]:
# Concat the frames!

# First we have to initialize the frame
df = pd.DataFrame(columns=['title', 'author', 'score', 'post_id','post_url',
                                                       'comments','type','upvote_ratio'])

# Then load and loop through 
for name, champ_name in list(zip(read_name, clean_champ_names)):
    temp_df = pd.read_csv(name)
    temp_df['Champion'] = champ_name
    df = pd.concat([df, temp_df], ignore_index=True)

In [178]:
# df.to_csv('all_champs_df.csv')


# Just a quick look at the dataframe...

In [196]:
# Quick look at post with the least upvote ratio 
df.loc[df['upvote_ratio'] == df['upvote_ratio'].min()]
# https://www.reddit.com/r/IreliaMains/comments/78bcla/irelias_reworked_abilities/
# Turn out it is thread that was full of fake rumors about irelia nerfs.

,Champion,Unnamed: 0,author,comments,post_id,post_url,score,title,type,upvote_ratio
1834,Irelia,34.0,ThunderousBlade,[{Redditor(name='Wixxus'): 'Thread has been co...,78bcla,https://www.reddit.com/r/IreliaMains/comments/...,30,Irelia's Reworked abilities,youtube.com,0.55

In [202]:
# Find champion with lowest upvote ratio
grouped = df.groupby('Champion').mean().reset_index()
grouped.sort_values('upvote_ratio', ascending=False)
# df.groupby('Champion')['upvote_ratio'].mean()

          Champion  Unnamed: 0  upvote_ratio
73            Nami        24.5        0.9836
45            Jhin        24.5        0.9830
98            Sion        24.5        0.9816
65             Lux        24.5        0.9790
23            Ekko        24.5        0.9790
10            Bard        24.5        0.9786
107          Talon        24.5        0.9782
49         Karthus        24.5        0.9772
19          Darius        24.5        0.9772
56         Kindred        24.5        0.9768
8    Aurelion_Sol_        24.5        0.9768
91          Rumble        24.5        0.9762
31       Gangplank        24.5        0.9762
77        Nocturne        24.5        0.9760
132         Yorick        24.5        0.9748
9             Azir        24.5        0.9738
46            Jinx        24.5        0.9736
90           Riven        24.5        0.9736
106        Taliyah        24.5        0.9732
138           Zyra        24.5        0.9730
61           Leona        24.5        0.9728
80         Orianna        24.5        0.9714
71     Mordekaiser        24.5        0.9712
110         Thresh        24.5        0.9710
95            Shen        24.5        0.9708
1             Ahri        24.5        0.9706
57            Kled        24.5        0.9704
136         Zilean        24.5        0.9704
43             Jax        24.5        0.9702
109          Teemo        24.5        0.9702
..             ...         ...           ...
44           Jayce        24.5        0.9460
68          Maokai        24.5        0.9458
17         ChoGath        24.5        0.9456
66        Malphite        24.5        0.9438
3          Alistar        24.5        0.9438
130        XinZhao        24.5        0.9434
97          Singed        24.5        0.9430
32           Garen        24.5        0.9424
18           Corki        24.5        0.9422
103          Swain        24.5        0.9422
119          Vayne        24.5        0.9418
36         Hecarim        24.5        0.9414
82        Pantheon        24.5        0.9390
76         Nidalee        24.5        0.9388
114    TwistedFate        24.5        0.9382
129         Xerath        24.5        0.9380
11      Blitzcrank        24.5        0.9374
69        MasterYi        24.5        0.9364
111       Tristana        24.5        0.9358
4            Amumu        24.5        0.9356
116           Udyr        24.5        0.9350
60          LeeSin        24.5        0.9348
35          Graves        24.5        0.9346
25         Evelynn        24.5        0.9332
118          Varus        24.5        0.9330
79            Olaf        24.5        0.9328
52           Kayle        24.5        0.9296
93         Sejuani        24.5        0.9292
133            Zac        24.5        0.9250
30           Galio        24.5        0.9028

[139 rows x 3 columns]

In [ ]:
# Get counts for types of media content 

# media_dict = {}

# for champ in clean_champ_names:
#     temp_df = df.loc[df['Champion'] == champ]
    
# On closer look type value doesn't appear to be that accuracte...abandon for now

In [236]:
# df['author'].value_counts() #
for champ in clean_champ_names:
    temp_df = df.loc[df['Champion'] == champ]
    for auth, posts in zip(temp_df['author'].value_counts().index, temp_df['author'].value_counts().values):
        if posts > 4:
            print(champ, auth, posts)
    print()

Aatrox AHare115 6

Ahri KindRavenn 5

Akali ProfessorAkaliOnYT 5

Amumu SpudMonkApe 9





Azir LordAzir 6
Azir Azukus 5


Blitzcrank Miss_Ally 7



Caitlyn MiniBus93 21


Cassiopeia heroicsej 6



Darius Penguinmull 7

Diana Stefanpkh 6

DrMundo fart_the_gr8 27





Fiddlesticks Charizardmain 6

Fiora ScrubHard 15
Fiora gubigubi 5




Garen BlueFire376 5



Graves IWantMyCigar 6



Irelia qhfreddy 5


JarvanIV KingNidhogg 18

Jax Jaxing-Is-MyDna 5

Jayce DovahkiinHero 6
Jayce Full_Metal_Jayce 5

Jhin SheepHerdr 5



Karthus Deus-Ex-Lacrymae 12

Kassadin the_fredblubby 6




Kennen HeyItsMezz 6




LeBlanc ItzBleKz 7


Leona i0ki 6

Lissandra Elsa_of_Garendel 7


Lulu Selkedoom 5






Mordekaiser Armthehobos 6



Nasus Osoguineapig 8


Nidalee Call_me_Nidalee 7

Nocturne RuneKatashima 6

Nunu candoodle 14

Olaf olaf_only 8
Olaf Dontfeedthecroc 7
Olaf BestOlafNA 5



Pantheon fccarminati 5

Poppy XxG0pNiKxX 13





Renekton Godrekton 6



Rumble Dangiuz 6

Ryze SoupRyze 18



Shyvana Finalixzer 8
Shyvana Antarlia 7



Sona AkemiSen 7


Swain spyrothefox 6

Syndra OverlordForte 5



Talon RawStanky 6








Udyr GoLeonzz 7


Varus Deejayce 6
Varus RiveliaSenpai 5



Vi Ryuuzaki13 7

Viktor Arcyvilk 7

Vladimir Elite500 8
Vladimir CalmYourNeckbeard 5

Volibear i_love_juggs 15


Wukong AllorimNA 7





Yorick Ducksen 8
Yorick Facelift6 5

Zed hahahasplat 8


Zilean Only_Zilean_NA 6


Zyra Umarrii 5


Velkoz Nayqua 7


Sivir Jeedos 10



Lux Fiersome3 5


Jinx F4LLENIGHT_LOL_JINX 7
Jinx robot_mars 5

Janna WindforceJanna 10

In [231]:
temp_df['author'].value_counts.index

AttributeError: 'function' object has no attribute 'index'

# Figuring out comment parser for graphing notebook

In [179]:
# temp_df = pd.read_csv('Kledmains_df.csv')
# temp_df['Champion'] = 'Kled'
# temp_df.head()

In [151]:


# for i in range(temp_df['comments'].shape[0]):
#     comment = temp_df['comments'][i]
#     comment = comment[1:len(comment)-1] # get rid of [ ]
    
#     comments_w_child = comment.split('},')
#     for coms in comments_w_child:
#         new_comment = strip_comment(coms)
#         print(new_comment)
#         print()

In [180]:
# len(combbbment_parser(temp_df))

In [ ]:
def strip_comment(s):
    record = False
    new_s = ''
    idx = 0
    for i in range(len(s)):
        window = s[i:i+3]
        if window == "'):":
            idx = i+3
            break 
    if s[len(s)-2:] == "'}":
        new_s = s[idx:len(s)-1]
        new_s = new_s.strip()
        return new_s
    new_s = s[idx:]
    new_s = new_s.strip()
    return new_s

In [153]:
def comment_parser(temp_df):
    
    comment_list = []

    for i in range(temp_df['comments'].shape[0]):
        comment = temp_df['comments'][i]
        comment = comment[1:len(comment)-1] # get rid of [ ]


        comments_w_child = comment.split('},')
        for coms in comments_w_child:
            new_comment = strip_comment(coms)
            comment_list.append(new_comment)
            
    return comment_list

In [159]:
test5 = comment_parser(temp_df)

In [160]:
test3 = ['Kled'] * len(comment_parser(temp_df))

In [168]:
# list(zip(test3, test5))
# ' '.join(test5)
len(test5)

530